import type {
  Media,
  NewsEntry,
  NewsListItem,
  PageDto,
  Program,
  Project,
  ProjectListItem,
  Service,
  SiteSettingDto,
} from "./api";

const noMedia: Media = null;

const services: Service[] = [
  {
    id: 1,
    name: "Web Design",
    slug: "web-design",
    description: "Design systems and marketing websites focused on clarity and conversion.",
    order: 1,
    seo: {
      metaTitle: "Web Design Services | Conc Website",
      metaDescription: "Design systems and service pages focused on clarity, structure, and conversion.",
      canonicalUrl: "https://conc.example/services/web-design",
      noIndex: false,
      metaImage: null,
    },
    icon: noMedia,
  },
  {
    id: 2,
    name: "Strapi Development",
    slug: "strapi-development",
    description: "Content architecture, API modeling, and custom CMS workflows on Strapi.",
    order: 2,
    seo: {
      metaTitle: "Strapi Development | Conc Website",
      metaDescription: "Strapi content modeling, APIs, and editorial workflows for service websites.",
      canonicalUrl: "https://conc.example/services/strapi-development",
      noIndex: false,
      metaImage: null,
    },
    icon: noMedia,
  },
  {
    id: 3,
    name: "Frontend Engineering",
    slug: "frontend-engineering",
    description: "Fast, maintainable interfaces built for modern React and headless CMS stacks.",
    order: 3,
    seo: {
      metaTitle: "Frontend Engineering | Conc Website",
      metaDescription: "Frontend implementation for headless CMS websites and reusable content systems.",
      canonicalUrl: "https://conc.example/services/frontend-engineering",
      noIndex: false,
      metaImage: null,
    },
    icon: noMedia,
  },
];

const projects: Project[] = [
  {
    id: 1,
    title: "Conc Website Relaunch",
    slug: "conc-website-relaunch",
    summary: "A modern marketing site with a reusable page builder and clearer service positioning.",
    content:
      "<p>We designed and implemented a new content model for landing pages, editorial content, reusable sections, and case studies.</p>",
    clientName: "Conc Studio",
    completedDate: "2026-02-14",
    featured: true,
    order: 1,
    seo: {
      metaTitle: "Conc Website Relaunch Project",
      metaDescription: "A project showcasing a reusable page builder and clearer service positioning.",
      canonicalUrl: "https://conc.example/projects/conc-website-relaunch",
      noIndex: false,
      metaImage: null,
    },
    coverImage: noMedia,
    gallery: [],
    services: services.slice(0, 2),
  },
  {
    id: 2,
    title: "Editorial Operations Toolkit",
    slug: "editorial-operations-toolkit",
    summary: "A headless CMS setup for teams that publish across service pages, blog content, and campaigns.",
    content: "<p>This project focused on schema consistency, editorial speed, and frontend-friendly API shapes.</p>",
    clientName: "Internal Prototype",
    completedDate: "2026-03-05",
    featured: false,
    order: 2,
    seo: {
      metaTitle: "Editorial Operations Toolkit Project",
      metaDescription: "A headless CMS setup for marketing pages, campaigns, and editorial workflows.",
      canonicalUrl: "https://conc.example/projects/editorial-operations-toolkit",
      noIndex: false,
      metaImage: null,
    },
    coverImage: noMedia,
    gallery: [],
    services,
  },
];

const newsEntries: NewsEntry[] = [
  {
    id: 1,
    title: "Launching The New Conc Website Content Platform",
    slug: "launching-the-new-conc-website-content-platform",
    content:
      "<p>We rebuilt the website content model to support reusable page sections, richer editorial workflows, and faster publishing.</p>",
    publishedDate: "2026-03-01",
    seo: {
      metaTitle: "Launching The New Conc Website Content Platform",
      metaDescription: "How the new content platform improves editorial workflows and page building.",
      canonicalUrl: "https://conc.example/news/launching-the-new-conc-website-content-platform",
      noIndex: false,
      metaImage: null,
    },
    coverImage: noMedia,
  },
  {
    id: 2,
    title: "How We Structure Page Builder Content In Strapi",
    slug: "how-we-structure-page-builder-content-in-strapi",
    content:
      "<p>This article explains how dynamic zones, shared components, and editorial naming conventions help teams ship faster.</p>",
    publishedDate: "2026-03-10",
    seo: {
      metaTitle: "How We Structure Page Builder Content In Strapi",
      metaDescription: "A practical look at dynamic zones, reusable components, and editor-friendly schemas.",
      canonicalUrl: "https://conc.example/news/how-we-structure-page-builder-content-in-strapi",
      noIndex: false,
      metaImage: null,
    },
    coverImage: noMedia,
  },
  {
    id: 3,
    title: "Project Spotlight: Headless Content For A Service Brand",
    slug: "project-spotlight-headless-content-for-a-service-brand",
    content:
      "<p>A case study on using Strapi to power landing pages, case studies, news, and reusable content blocks.</p>",
    publishedDate: "2026-03-18",
    seo: {
      metaTitle: "Project Spotlight: Headless Content For A Service Brand",
      metaDescription: "A sample case study on using Strapi for marketing pages and editorial content.",
      canonicalUrl: "https://conc.example/news/project-spotlight-headless-content-for-a-service-brand",
      noIndex: false,
      metaImage: null,
    },
    coverImage: noMedia,
  },
];

const programs: Program[] = [
  {
    id: 1,
    title: "Strategic Content Operations Bootcamp",
    slug: "strategic-content-operations-bootcamp",
    category: "Training Program",
    format: "Hybrid Intensive",
    dateLabel: "12-13 April 2026",
    startsAt: "2026-04-12",
    duration: "2 days",
    location: "Bangkok + Online",
    fee: "THB 12,900",
    audience: "Marketing leads, content managers, and digital transformation teams",
    summary:
      "A practical bootcamp for teams that need a clearer operating model for content planning, governance, and delivery across web channels.",
    overview: [
      "This program focuses on turning fragmented publishing work into a repeatable content operations system.",
      "Participants work through planning models, ownership design, workflow checkpoints, and practical templates they can reuse after the workshop.",
    ],
    outcomes: [
      "Map content ownership across teams and channels",
      "Design a realistic editorial workflow with approvals and handoffs",
      "Identify the minimum content system needed before scaling tooling",
    ],
    seats: 24,
    registrationEnabled: true,
    seo: {
      metaTitle: "Strategic Content Operations Bootcamp",
      metaDescription: "A practical bootcamp on content planning, governance, and delivery systems for digital teams.",
      canonicalUrl: "https://conc.example/programs/strategic-content-operations-bootcamp",
      noIndex: false,
      metaImage: null,
    },
  },
  {
    id: 2,
    title: "Headless CMS Implementation for Service Teams",
    slug: "headless-cms-implementation-for-service-teams",
    category: "Training Program",
    format: "Onsite Workshop",
    dateLabel: "28 April 2026",
    startsAt: "2026-04-28",
    duration: "1 day",
    location: "CONC Learning Studio",
    fee: "THB 8,500",
    audience: "Frontend developers, product owners, and technical marketers",
    summary:
      "A hands-on workshop on content modeling, API shape design, and frontend integration patterns for teams moving to a headless CMS stack.",
    overview: [
      "The workshop uses a service-website scenario to explain how content models, reusable components, and frontend DTOs fit together.",
      "It is designed for teams that need a shared technical and editorial vocabulary before implementation starts.",
    ],
    outcomes: [
      "Define collection types and reusable components for a real website model",
      "Reduce frontend coupling by shaping CMS responses for actual page needs",
      "Plan a phased migration path from static pages to structured content",
    ],
    seats: 18,
    registrationEnabled: true,
    seo: {
      metaTitle: "Headless CMS Implementation for Service Teams",
      metaDescription: "A workshop on content modeling, API design, and frontend integration for service teams.",
      canonicalUrl: "https://conc.example/programs/headless-cms-implementation-for-service-teams",
      noIndex: false,
      metaImage: null,
    },
  },
  {
    id: 3,
    title: "Executive Communication Design for Digital Teams",
    slug: "executive-communication-design-for-digital-teams",
    category: "Training Program",
    format: "Live Online Session",
    dateLabel: "15 May 2026",
    startsAt: "2026-05-15",
    duration: "Half day",
    location: "Zoom",
    fee: "THB 4,900",
    audience: "Leadership teams, PMs, consultants, and internal communication owners",
    summary:
      "A concise training session on structuring high-stakes updates, strategy decks, and digital communication so decisions can move faster.",
    overview: [
      "The session covers message framing, narrative sequencing, and visual simplification for decision-oriented communication.",
      "Participants leave with a reusable structure for turning dense information into clearer executive communication.",
    ],
    outcomes: [
      "Structure updates for faster decision-making",
      "Reduce ambiguity in strategic communication",
      "Create cleaner artifacts for executives and stakeholder groups",
    ],
    seats: 40,
    registrationEnabled: false,
    seo: {
      metaTitle: "Executive Communication Design for Digital Teams",
      metaDescription: "A short training session on message framing, narrative sequencing, and executive communication.",
      canonicalUrl: "https://conc.example/programs/executive-communication-design-for-digital-teams",
      noIndex: false,
      metaImage: null,
    },
  },
];

const siteSetting: SiteSettingDto = {
  id: 1,
  siteName: "Conc Website",
  siteDescription: "Sample content for a Strapi-powered service website with a reusable page builder.",
  contactEmail: "hello@conc.example",
  contactPhone: "+66 2 000 0000",
  address: "Bangkok, Thailand",
  facebookUrl: "https://facebook.com/",
  lineUrl: "https://line.me/",
  youtubeUrl: "https://youtube.com/",
  copyrightText: "© 2026 Conc Website. All rights reserved.",
  logo: null,
};

const pages: Record<string, PageDto> = {
  home: {
    id: 1,
    slug: "home",
    title: "Home",
    seo: {
      metaTitle: "Conc Website | Strapi-Powered Service Website",
      metaDescription: "A sample homepage powered by Strapi with reusable sections and frontend-friendly APIs.",
      canonicalUrl: "https://conc.example/",
      noIndex: false,
      metaImage: null,
    },
    sections: [
      {
        type: "hero",
        id: 1,
        eyebrow: "Conc Website",
        title: "A flexible Strapi page builder for service-led websites",
        description: "Manage services, projects, news, and reusable landing-page sections from one editorial workflow.",
        primaryButtonText: "View Services",
        primaryButtonUrl: "/services",
        secondaryButtonText: "See Projects",
        secondaryButtonUrl: "/projects",
        backgroundImage: null,
      },
      {
        type: "services-list",
        id: 2,
        eyebrow: "Capabilities",
        title: "What we help teams ship",
        description: "A small set of focused services tied directly to the content model and frontend output.",
        limit: 3,
        viewAllText: "View all services",
        viewAllUrl: "/services",
        services,
      },
      {
        type: "projects-list",
        id: 3,
        eyebrow: "Selected Work",
        title: "Recent projects",
        description: "Structured case studies that can be reused across marketing pages and editorial content.",
        limit: 2,
        viewAllText: "Browse all projects",
        viewAllUrl: "/projects",
        projects,
      },
      {
        type: "stats",
        id: 4,
        eyebrow: "Impact",
        title: "Content operations made easier",
        description: "A cleaner schema gives editors a faster way to publish and maintain pages.",
        items: [
          { id: 1, value: "10", suffix: "+", label: "Reusable sections", description: "Page-builder blocks available to editors out of the box." },
          { id: 2, value: "3", suffix: null, label: "Core collections", description: "Services, projects, and news organized for easy reuse." },
          { id: 3, value: "1", suffix: null, label: "Single source", description: "One CMS model for homepage, landing pages, and editorial content." },
        ],
      },
      {
        type: "team",
        id: 5,
        eyebrow: "Team",
        title: "People behind the build",
        description: "A sample team section to help shape the frontend layout and admin workflow.",
        members: [
          {
            id: 1,
            name: "Sathorn",
            role: "Product Lead",
            bio: "Defines the content model and ensures the website structure supports the real editorial workflow.",
            linkedinUrl: "https://www.linkedin.com/",
            email: "sathorn@example.com",
            photo: null,
          },
          {
            id: 2,
            name: "Ariya",
            role: "Frontend Engineer",
            bio: "Builds the page renderer and integrates dynamic-zone content into the frontend experience.",
            linkedinUrl: "https://www.linkedin.com/",
            email: "ariya@example.com",
            photo: null,
          },
        ],
      },
      {
        type: "testimonial",
        id: 6,
        eyebrow: "Feedback",
        title: "What this setup enables",
        description: "Sample testimonials for frontend layout and editorial review.",
        items: [
          {
            id: 1,
            quote: "The new content model makes it much easier to launch pages without asking developers for every change.",
            authorName: "Editorial Team",
            authorRole: "Content Operations",
            authorCompany: "Conc Studio",
            authorAvatar: null,
          },
          {
            id: 2,
            quote: "Reusable sections keep the frontend clean and the admin experience predictable.",
            authorName: "Engineering Team",
            authorRole: "Frontend Development",
            authorCompany: "Conc Studio",
            authorAvatar: null,
          },
        ],
      },
      {
        type: "faq",
        id: 7,
        eyebrow: "FAQ",
        title: "Questions teams usually ask",
        description: "Starter answers for common implementation and editorial topics.",
        items: [
          {
            id: 1,
            question: "Can editors build multiple pages with the same sections?",
            answer: "<p>Yes. The page builder uses reusable component schemas so the same section types can be mixed per page.</p>",
          },
          {
            id: 2,
            question: "Can projects, services, and news be reused across sections?",
            answer: "<p>Yes. The list sections are relation-based, so editors can select existing entries instead of duplicating content.</p>",
          },
        ],
      },
      {
        type: "news-list",
        id: 8,
        eyebrow: "Updates",
        title: "Latest news",
        description: "Editorial content tied into the same CMS model as the marketing pages.",
        limit: 3,
        viewAllText: "Read all news",
        viewAllUrl: "/news",
        newsEntries,
      },
      {
        type: "gallery",
        id: 9,
        eyebrow: "Gallery",
        title: "Visual placeholders for layout testing",
        description: "Media can be added later in the admin; this section exists now so the frontend can support it.",
        layout: "grid",
        images: [],
      },
      {
        type: "call-to-action",
        id: 10,
        eyebrow: "Next Step",
        title: "Ready to connect the frontend to this content model?",
        description: "Use this sample CTA block to validate button styling, spacing, and route handling.",
        buttonText: "Contact Us",
        buttonUrl: "/contact",
        backgroundImage: null,
      },
    ],
  },
  about: {
    id: 2,
    slug: "about",
    title: "About",
    seo: {
      metaTitle: "About CONC",
      metaDescription: "Learn how CONC approaches content systems, service websites, and maintainable frontend delivery.",
      canonicalUrl: "https://conc.example/about",
      noIndex: false,
      metaImage: null,
    },
    sections: [
      {
        type: "hero",
        id: 11,
        eyebrow: "About CONC",
        title: "A service-led team focused on structured digital experiences",
        description: "We help organizations clarify their offer, structure their content, and ship websites that are easier to maintain.",
        primaryButtonText: "Contact Us",
        primaryButtonUrl: "/contact",
        secondaryButtonText: "See Projects",
        secondaryButtonUrl: "/projects",
        backgroundImage: null,
      },
      {
        type: "rich-text",
        id: 12,
        eyebrow: "Who We Are",
        title: "Built for editorial clarity and practical delivery",
        description: null,
        body: "<p>CONC works at the intersection of content strategy, information architecture, and frontend delivery. We focus on helping teams publish with less friction and keep their websites maintainable over time.</p><p>Our approach prioritizes reusable systems over one-off page builds so that marketing, editorial, and product teams can move faster together.</p>",
      },
      {
        type: "stats",
        id: 13,
        eyebrow: "What Matters",
        title: "A working model for smaller teams",
        description: "A concise set of operating principles to shape the about page layout.",
        items: [
          { id: 4, value: "1", suffix: null, label: "Shared content model", description: "One structure for pages, projects, and editorial content." },
          { id: 5, value: "3", suffix: null, label: "Core disciplines", description: "Strategy, content systems, and frontend implementation." },
          { id: 6, value: "100%", suffix: null, label: "Reusable sections", description: "Page sections designed to be mixed and reused across routes." },
        ],
      },
      {
        type: "call-to-action",
        id: 14,
        eyebrow: "Next Step",
        title: "Need a clearer content system for your website?",
        description: "Use this page as a reusable about-page reference and route users to contact.",
        buttonText: "Talk to CONC",
        buttonUrl: "/contact",
        backgroundImage: null,
      },
    ],
  },
  executive: {
    id: 8,
    slug: "executive",
    title: "Executive",
    seo: {
      metaTitle: "Executive | CONC",
      metaDescription: "Executive direction, stewardship, and institutional leadership context for CONC.",
      canonicalUrl: "https://conc.example/about/executive",
      noIndex: false,
      metaImage: null,
    },
    sections: [
      {
        type: "hero",
        id: 31,
        eyebrow: "About Us",
        title: "Executive",
        description:
          "CONC brings together academic credibility and market-facing experience to support executive development, strategic communication, and capability building across leadership teams.",
        primaryButtonText: "Contact Us",
        primaryButtonUrl: "/contact",
        secondaryButtonText: "About CONC",
        secondaryButtonUrl: "/about",
        backgroundImage: null,
      },
      {
        type: "rich-text",
        id: 32,
        eyebrow: "Strategic Direction",
        title: "Leadership aligned to institutional relevance",
        description: null,
        body: "<p>Executive oversight focuses on keeping consulting, coaching, and learning services aligned with institutional goals and the practical needs of partner organizations.</p><p>The center operates with a mix of academic, advisory, and operational perspectives so programs can address leadership, communication, and transformation work in one place.</p><p>Leadership also maintains relationships with university stakeholders, industry partners, and client organizations to ensure quality, continuity, and long-term relevance.</p>",
      },
    ],
  },
  philosophy: {
    id: 9,
    slug: "philosophy",
    title: "Philosophy",
    seo: {
      metaTitle: "Philosophy | CONC",
      metaDescription: "How CONC approaches practical learning, evidence-led work, and accountable organizational development.",
      canonicalUrl: "https://conc.example/about/philosophy",
      noIndex: false,
      metaImage: null,
    },
    sections: [
      {
        type: "hero",
        id: 33,
        eyebrow: "About Us",
        title: "Philosophy",
        description:
          "CONC works as a university-linked consulting and coaching center that values disciplined thinking, practical execution, and measurable development for leaders, teams, and organizations.",
        primaryButtonText: "See Programs",
        primaryButtonUrl: "/programs",
        secondaryButtonText: "Contact Us",
        secondaryButtonUrl: "/contact",
        backgroundImage: null,
      },
      {
        type: "rich-text",
        id: 34,
        eyebrow: "Principles",
        title: "Learning through practice and accountable delivery",
        description: null,
        body: "<p>Programs are designed around real organizational challenges so participants can translate frameworks into decisions, communication, and delivery habits that hold up in actual work.</p><p>We favor structured diagnosis, stakeholder listening, and clear success criteria before recommending interventions, content strategy, or executive coaching pathways.</p><p>Coaching and consulting are paired with explicit outcomes, follow-through checkpoints, and operational clarity so development work does not stop at inspiration.</p>",
      },
    ],
  },
  facilities: {
    id: 10,
    slug: "facilities",
    title: "Facilities",
    seo: {
      metaTitle: "Facilities | CONC",
      metaDescription: "Training rooms, meeting space, and hybrid-ready facilities that support CONC programs and engagements.",
      canonicalUrl: "https://conc.example/about/facilities",
      noIndex: false,
      metaImage: null,
    },
    sections: [
      {
        type: "hero",
        id: 35,
        eyebrow: "About Us",
        title: "Facilities",
        description:
          "The center supports workshops, coaching, and executive engagement with spaces and formats that can accommodate focused discussion, collaborative sessions, and hybrid delivery.",
        primaryButtonText: "Contact Us",
        primaryButtonUrl: "/contact",
        secondaryButtonText: "About CONC",
        secondaryButtonUrl: "/about",
        backgroundImage: null,
      },
      {
        type: "rich-text",
        id: 36,
        eyebrow: "Spaces",
        title: "Built for workshops, executive sessions, and blended delivery",
        description: null,
        body: "<p>Facilities include training rooms configured for seminars, capability workshops, and intensive short-format programs with layouts that support both instruction and group work.</p><p>Executive meeting spaces support coaching conversations, planning sessions, and partner consultations that require privacy and concentration.</p><p>Hybrid session support makes it possible to combine on-site facilitation with remote attendance and documentation workflows.</p>",
      },
    ],
  },
  contact: {
    id: 3,
    slug: "contact",
    title: "Contact",
    seo: {
      metaTitle: "Contact CONC",
      metaDescription: "Get in touch with CONC about content modeling, frontend delivery, and service website implementation.",
      canonicalUrl: "https://conc.example/contact",
      noIndex: false,
      metaImage: null,
    },
    sections: [
      {
        type: "hero",
        id: 15,
        eyebrow: "Contact",
        title: "Start with the problem you need to solve",
        description: "Reach out about content modeling, service websites, frontend implementation, or editorial workflows.",
        primaryButtonText: "Email Us",
        primaryButtonUrl: "mailto:hello@conc.example",
        secondaryButtonText: "Read About Us",
        secondaryButtonUrl: "/about",
        backgroundImage: null,
      },
      {
        type: "rich-text",
        id: 16,
        eyebrow: "Contact Details",
        title: "Ways to reach the team",
        description: null,
        body: "<p><strong>Email:</strong> hello@conc.example</p><p><strong>Phone:</strong> +66 2 000 0000</p><p><strong>Address:</strong> Bangkok, Thailand</p><p>Share your current setup, what is blocking the team, and what outcome you want from the next iteration of the site.</p>",
      },
      {
        type: "faq",
        id: 17,
        eyebrow: "Before We Start",
        title: "Useful questions to answer first",
        description: "This gives the contact page meaningful structure while testing reusable sections.",
        items: [
          {
            id: 3,
            question: "What should we send in the first message?",
            answer: "<p>Include your current website or content system, the main problem, and the timeline you are working against.</p>",
          },
          {
            id: 4,
            question: "Can this setup work for small teams?",
            answer: "<p>Yes. The model is intentionally lean so a small team can maintain it without a large editorial operation.</p>",
          },
        ],
      },
    ],
  },
  services: {
    id: 4,
    slug: "services",
    title: "Services",
    seo: {
      metaTitle: "Services | CONC",
      metaDescription: "Explore the sample service offering used across the CONC website content model.",
      canonicalUrl: "https://conc.example/services",
      noIndex: false,
      metaImage: null,
    },
    sections: [
      {
        type: "hero",
        id: 18,
        eyebrow: "Services",
        title: "A focused service set built to support content and delivery",
        description: "This sample services page mirrors the frontend list route and helps editors validate service cards, copy, and linking.",
        primaryButtonText: "View Projects",
        primaryButtonUrl: "/projects",
        secondaryButtonText: "Contact Us",
        secondaryButtonUrl: "/contact",
        backgroundImage: null,
      },
      {
        type: "services-list",
        id: 19,
        eyebrow: "Capabilities",
        title: "Published services",
        description: "Use this section to curate the service entries that should appear on the services landing page.",
        limit: 6,
        viewAllText: "All services",
        viewAllUrl: "/services",
        services,
      },
      {
        type: "call-to-action",
        id: 20,
        eyebrow: "Next Step",
        title: "Need help shaping a service-led website?",
        description: "Route visitors from the service listing into a conversation about structure, delivery, and CMS setup.",
        buttonText: "Talk to CONC",
        buttonUrl: "/contact",
        backgroundImage: null,
      },
    ],
  },
  projects: {
    id: 5,
    slug: "projects",
    title: "Projects",
    seo: {
      metaTitle: "Projects | CONC",
      metaDescription: "Review sample projects that show how CONC structures reusable content and frontend delivery.",
      canonicalUrl: "https://conc.example/projects",
      noIndex: false,
      metaImage: null,
    },
    sections: [
      {
        type: "hero",
        id: 21,
        eyebrow: "Projects",
        title: "Selected work built around reusable content systems",
        description: "This page gives editors a sample layout for project overviews while keeping the same content model used by the frontend.",
        primaryButtonText: "See Services",
        primaryButtonUrl: "/services",
        secondaryButtonText: "Read News",
        secondaryButtonUrl: "/news",
        backgroundImage: null,
      },
      {
        type: "projects-list",
        id: 22,
        eyebrow: "Case Studies",
        title: "Published projects",
        description: "Curate project entries for the main projects landing page or campaign-style showcase pages.",
        limit: 6,
        viewAllText: "All projects",
        viewAllUrl: "/projects",
        projects,
      },
      {
        type: "call-to-action",
        id: 23,
        eyebrow: "Start A Project",
        title: "Want a more maintainable delivery model?",
        description: "Use the project page template to move from examples into a concrete implementation conversation.",
        buttonText: "Contact Us",
        buttonUrl: "/contact",
        backgroundImage: null,
      },
    ],
  },
  news: {
    id: 6,
    slug: "news",
    title: "News",
    seo: {
      metaTitle: "News | CONC",
      metaDescription: "Sample editorial updates published from the same Strapi content system as the website pages.",
      canonicalUrl: "https://conc.example/news",
      noIndex: false,
      metaImage: null,
    },
    sections: [
      {
        type: "hero",
        id: 24,
        eyebrow: "News",
        title: "Editorial updates published from the same content system",
        description: "This sample archive page shows how news entries can be reused inside a page-builder route while still supporting detail pages.",
        primaryButtonText: "Browse Projects",
        primaryButtonUrl: "/projects",
        secondaryButtonText: "About CONC",
        secondaryButtonUrl: "/about",
        backgroundImage: null,
      },
      {
        type: "news-list",
        id: 25,
        eyebrow: "Latest Updates",
        title: "Published news entries",
        description: "Editors can reuse this section for a main archive, a homepage block, or a campaign landing page.",
        limit: 6,
        viewAllText: "All news",
        viewAllUrl: "/news",
        newsEntries,
      },
      {
        type: "call-to-action",
        id: 26,
        eyebrow: "Stay In Touch",
        title: "Want updates on content systems and delivery?",
        description: "Keep the archive connected to a clear next step instead of ending the user journey at the list.",
        buttonText: "Contact Us",
        buttonUrl: "/contact",
        backgroundImage: null,
      },
    ],
  },
  programs: {
    id: 7,
    slug: "programs",
    title: "Programs",
    seo: {
      metaTitle: "Programs | CONC",
      metaDescription: "Browse sample training programs and registration-ready offerings managed in Strapi.",
      canonicalUrl: "https://conc.example/programs",
      noIndex: false,
      metaImage: null,
    },
    sections: [
      {
        type: "hero",
        id: 27,
        eyebrow: "CONC Programs",
        title: "Applied training programs for teams that need sharper digital execution",
        description: "Browse sample CONC learning tracks built around content operations, headless implementation, and communication clarity. Each program is designed to move from theory into decisions, tools, and practical team workflows.",
        primaryButtonText: "Explore Programs",
        primaryButtonUrl: "#upcoming-cohorts",
        secondaryButtonText: "Ask About Custom Training",
        secondaryButtonUrl: "/contact",
        backgroundImage: null,
      },
      {
        type: "stats",
        id: 30,
        eyebrow: "Why These Programs Work",
        title: "Short format, practical outputs, and clear next steps",
        description: "The sample catalog is structured to help editors present programs as concrete working sessions instead of generic course descriptions.",
        items: [
          {
            value: "3",
            suffix: "",
            label: "Sample tracks",
            description: "Content ops, headless CMS implementation, and executive communication formats ready for listing pages.",
          },
          {
            value: "1",
            suffix: " team",
            label: "Shared workflow",
            description: "Each program is framed around what a team can align on and implement together after the session.",
          },
          {
            value: "90",
            suffix: " days",
            label: "Implementation horizon",
            description: "The sample copy points participants toward concrete rollout decisions after the training rather than ending at the workshop.",
          },
        ],
      },
      {
        type: "programs-list",
        id: 28,
        eyebrow: "Upcoming Cohorts",
        title: "Current and sample-ready training offers",
        description: "Use this listing block to surface active cohorts, show what each program is for, and route visitors into either direct registration or a custom training conversation.",
        limit: 6,
        viewAllText: "All programs",
        viewAllUrl: "/programs",
        programs,
      },
      {
        type: "call-to-action",
        id: 29,
        eyebrow: "Custom Training",
        title: "Need an in-house version shaped around your team?",
        description: "CONC can turn these public program outlines into a private cohort, leadership session, or working workshop aligned to your current delivery challenges.",
        buttonText: "Talk To CONC",
        buttonUrl: "/contact",
        backgroundImage: null,
      },
    ],
  },
  "privacy-policy": {
    id: 11,
    slug: "privacy-policy",
    title: "Privacy Policy",
    seo: {
      metaTitle: "Privacy Policy | CONC",
      metaDescription: "How CONC handles registration, inquiry, and website operation data.",
      canonicalUrl: "https://conc.example/privacy-policy",
      noIndex: false,
      metaImage: null,
    },
    sections: [
      {
        type: "hero",
        id: 37,
        eyebrow: "About Us",
        title: "Privacy Policy",
        description:
          "This website collects only the information required to respond to inquiries, process program registrations, and maintain reliable site operations. Personal data is handled with reasonable safeguards and limited to legitimate operational use.",
        primaryButtonText: "Contact Us",
        primaryButtonUrl: "/contact",
        secondaryButtonText: "Sitemap",
        secondaryButtonUrl: "/sitemap",
        backgroundImage: null,
      },
      {
        type: "rich-text",
        id: 38,
        eyebrow: "Data Handling",
        title: "Collection, use, and retention",
        description: null,
        body: "<p>Information submitted through contact and registration forms may include names, email addresses, phone numbers, organizational details, and any message content provided by the user.</p><p>Submitted information is used to respond to requests, evaluate registration eligibility, coordinate services, and maintain records necessary for program delivery and follow-up communication.</p><p>Information is retained only as long as needed for operational, academic, or compliance purposes. Access is limited to personnel and authorized collaborators who require it to perform their duties.</p>",
      },
    ],
  },
  sitemap: {
    id: 12,
    slug: "sitemap",
    title: "Sitemap",
    seo: {
      metaTitle: "Sitemap | CONC",
      metaDescription: "A quick reference to the public website structure and key content areas.",
      canonicalUrl: "https://conc.example/sitemap",
      noIndex: false,
      metaImage: null,
    },
    sections: [
      {
        type: "hero",
        id: 39,
        eyebrow: "About Us",
        title: "Sitemap",
        description: "A quick reference for the main public sections of the CONC website.",
        primaryButtonText: "Home",
        primaryButtonUrl: "/",
        secondaryButtonText: "Contact",
        secondaryButtonUrl: "/contact",
        backgroundImage: null,
      },
      {
        type: "rich-text",
        id: 40,
        eyebrow: "Structure",
        title: "Main pages and generated detail routes",
        description: null,
        body: "<p>Home, About, Services, Programs, Projects, News, and Contact provide the primary public navigation experience across the site.</p><p>Philosophy, Executive, Facilities, Sitemap, and Privacy Policy are grouped under About Us for institutional information and public reference material.</p><p>The site also includes generated detail pages for individual services, programs, projects, news articles, and program registration flows.</p>",
      },
    ],
  },
};

export const fallbackContent = {
  siteSetting,
  pages,
  services,
  projects,
  programs,
  newsEntries,
  projectList: projects.map<ProjectListItem>(({ id, title, slug, summary, clientName, completedDate, featured, order }) => ({
    id,
    title,
    slug,
    summary,
    clientName,
    completedDate,
    featured,
    order,
  })),
  newsList: newsEntries.map<NewsListItem>(({ id, title, slug, content, publishedDate }) => ({
    id,
    title,
    slug,
    content,
    publishedDate,
  })),
};
